

name: CucumberJavaProject

on: 
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: checkout code
      uses: actions/checkout@v4
   
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Run with Cucumber
      continue-on-error: true
      run: mvn test -Dcucumber.options="src/test/resources/features/NewFeature.feature"


    - name: git action adding test report
      run: |
               git config --global user.email "${{ secrets.GITHUBEMAIL }}"
               git config --global user.name "${{ secrets.GITHUBUSERNAME }}"
               git add target/cucumber-reports/Cucumber.json
               git commit -m "Adding latest cucumber json"
               git config --global pull.ff only 
               git push origin HEAD:main --force
               
    - name: Upload Json results in JIRS plugin
      run: |
            curl -X POST https://c4j.cucumber.io/ci/rest/api/results \
            -H 'authorization: Bearer ${{ secrets.Token }}' \
            -H 'content-type: multipart/form-data' \
            -F 'results_files =@"target/cucumber-reports/Cucumber.json"' \
            -F language=jvm
           
