

name: CucumberJavaProject

on: 
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
   
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Run with Cucumber
      continue-on-error: true
      run: mvn test -Dcucumber.options="src/test/resources/features/NewFeature.feature"
           
