
name: CucumberJavaProject

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: checkout code
      uses: actions/checkout@v4
   
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Run with Cucumber
      continue-on-error: true
      run: mvn test -Dcucumber.options="src/test/resources/features/NewFeature.feature" 
      
    - name: git action adding test report
      run: |
               git config --global user.email "${{ secrets.GITHUBEMAIL }}"
               git config --global user.name "${{ secrets.GITHUBUSERNAME }}"
               git add "target/cucumber-reports/Cucumber.json"
               git commit -m "adding json reports"
               git config --global pull.ff only 
               git push origin HEAD:master --force

    - name: Copy HTML report
      run: |
        mkdir -p CucumberJson
        cp target/cucumber-reports/Cucumber.json CucumberJson/   

    - name: Move HTML report to root
      run: |
        mv -Force target/cucumber-reports/Cucumber.json

    - name: Commit and push changes
      run:  |         
            git config --global user.name "${{ secrets.GITHUBEMAIL }}"         
            git config --global user.email "${{ secrets.GITHUBUSERNAME }}"         
            git add "Cucumber.json"         
            git commit -m "Pull json report from test-output folder"  
            git config --global pull.ff only
            git push origin HEAD:master --force    

                
    - name: Upload cucumber json test results
      uses: actions/upload-artifact@v4
      with:
            name: Cucumber Json reports
            path: "target/cucumber-reports/Cucumber.json"
            
    - name: Upload Json results in Cucumber for JIRA plugin
      run: |
            curl -X POST https://c4j.cucumber.io/ci/rest/api/results \
            -H 'authorization: Bearer ${{ secrets.Token }}' \
            -H 'content-type: multipart/form-data' \
            -F 'results_files[]=@"target/cucumber-reports/Cucumber.json"' \
            -F language=jvm
           
